[build-system]
requires = ['setuptools', 'wheel']

[tool.pytest.ini_options]
addopts = "--cov-report term-missing --cov-report xml --cov=docopt --mypy --mypy-ignore-missing-imports"
testpaths = [
    "./tests",
]